repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    exclude: ^acars-decoder-typescript/
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.3.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: prettier
        types: [javascript]
        additional_dependencies:
        -   prettier@2.1.2
        exclude: ^acars-decoder-typescript/
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.26.0
    hooks:
    -   id: eslint
        exclude: ^acars-decoder-typescript/
        additional_dependencies:
            -   eslint@4.15.0
            -   eslint-config-google@0.7.1
            -   babel-eslint@6.1.2
