repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
        exclude: ^(rootfs/webapp/static/css/other/|acars-decoder-typescript/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
    -   id: end-of-file-fixer
        exclude: ^(rootfs/webapp/static/css/other/|acars-decoder-typescript/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
    -   id: trailing-whitespace
        exclude: ^(rootfs/webapp/static/css/other/|acars-decoder-typescript/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
    -   id: requirements-txt-fixer
        exclude: ^(rootfs/webapp/static/css/other/|acars-decoder-typescript/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
    -   id: mixed-line-ending
        exclude: ^(rootfs/webapp/static/css/other/|acars-decoder-typescript/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
-   repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.1
    hooks:
    -   id: hadolint-system
        exclude: ^(rootfs/webapp/static/css/other/|acars-decoder-typescript/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
        args:
        - "--ignore"
        - "DL3003"
        - "--ignore"
        - "DL3006"
        - "--ignore"
        - "DL3010"
        - "--ignore"
        - "DL3008"
        - "--ignore"
        - "DL4001"
        - "--ignore"
        - "DL3007"
-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.3.2'  # Use the sha / tag you want to point at
    hooks:
    -   id: prettier
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
        -   prettier@2.3.2
        -   '@typescript-eslint/eslint-plugin'
        exclude: ^(rootfs/webapp/static/css/other/|acars-decoder-typescript/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.6.0
    hooks:
    -   id: eslint
        files: \.[j]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        exclude: ^(rootfs/webapp/static/css/other/|acars-decoder-typescript/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
        additional_dependencies:
            -   eslint@8.6.0
            -   eslint-config-google@0.7.1
            -   babel-eslint@10.1.0
#           -   '@typescript-eslint/eslint-plugin'
# -   repo: https://github.com/pre-commit/mirrors-csslint
#     rev: 'v1.0.5'  # Use the sha / tag you want to point at
#     hooks:
#     -   id: csslint
#         exclude: ^rootfs/webapp/static/css/other/
- repo: https://github.com/codespell-project/codespell.git
  rev: 'v2.1.0' # Use the sha / tag you want to point at
  hooks:
    -   id: codespell
        types: [text]
        exclude: ^(rootfs/webapp/static/css/other/|acars-decoder-typescript/|rootfs/webapp/static/js/other/|.+\.json|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other|rootfs/webapp/adsb.py|acarshub-typescript/src/interfaces.ts)
