---
name: Lint

on:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  # =====================================================================
  # Primary Lint job
  # =====================================================================
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: ${{ needs.skip-if-clean.outputs.skip != 'true' }} # <-- now valid in PRs

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run flake pre-commit hooks
        run: |
          nix develop -c bash -c '
            cd acarshub-react
            npm i
            just ci
          '
